# frozen_string_literal: true

source 'https://rubygems.org'

gem 'net-ssh', '~> 7.2'
gem 'net-scp', '~> 4.0'
gem 'semantic', '~> 1.6'
gem 'yaml', '~> 0.2'

group :development do
  gem 'rubocop', '~> 1.57'
  gem 'rubocop-performance', '~> 1.19'
  gem 'rubocop-rake', '~> 0.6'
  gem 'yard', '~> 0.9'
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'simplecov', '~> 0.22'
  gem 'webmock', '~> 3.19'
end
