# frozen_string_literal: true

source 'https://rubygems.org'

gem 'net-ssh', '~> 7.2'
gem 'net-scp', '~> 4.0'
gem 'logger', '~> 1.5'
gem 'json', '~> 2.7'
gem 'yaml', '~> 0.2'
gem 'erb', '~> 4.0'
gem 'optparse', '~> 0.3'

group :development do
  gem 'rubocop', '~> 1.60'
  gem 'rspec', '~> 3.13'
  gem 'pry', '~> 0.14'
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'simplecov', '~> 0.22'
  gem 'webmock', '~> 3.19'
end
